package com.uni.realt.controller.command;

public enum CommandName {
    GOTOHOMEPAGE, SEARCH, CLEAN, GOTOAGENTPAGE, GOTOOPERATIONPAGE, GOTOCLIENTPAGE,
    SORTBYCLIENT, SORTBYAGENT, SORTBYOPERATION, UPDATEORDER, UPDATEAGENT, UPDATEOPERATION,
    UPDATECLIENT, DELETEORDER, DELETEAGENT, DELETECLIENT, DELETEOPERATION, CREATENEWOPERATION,
    CREATENEWAGENT, CREATENEWORDER, CREATENEWCLIENT, GOTOUPDATEAGENTPAGE, GOTOUPDATECLIENTPAGE,
    GOTOUPDATEORDERPAGE, GOTOUPDATEOPERATIONPAGE
}
